version: '3'

services:
  frontend:
    container_name: react
    image: node:latest
    ports:
      - 3000:3000
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
  backend:
    container_name: nestjs
    image: node:latest
    ports:
    - 3001:3001
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    environment:
      DB_CONNECTION_STRING: mongodb+srv://zreit:88fKUzSBMBu9eM7@testapplication.i9pjh.mongodb.net/?retryWrites=true&w=majority
