version: '3'

services:
  backend:
    container_name: nestjs
    image: node:latest
    restart: always
    env_file:
      - .env
    ports:
      - 3000:3000
    build:
      context: .
      dockerfile: Dockerfile